//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocPlusApi.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public long Size { get; set; }
        public long Cursor { get; set; }
        public string Type { get; set; }
        public string Folder { get; set; }
        public int Clicks { get; set; }
        public System.DateTime Published { get; set; }
    }
}
